# MATH 210 Introduction to Mathematical Computing

## March 09, 2018

1. Linear algebra
    * Determinants, transpose, inverse, trace
    * Eigenvalues and eigenvectors
2. Example: Cayley Hamilton Theorem
3. Example: Symmetric matrices

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as spi
import scipy.linalg as la
from numpy.linalg import matrix_power as mpow
%matplotlib inline

## 1. Linear algebra with Scipy

Last time we defined functions for elementary matrix operations. Let's finish with the last one: `scale_row`.

In [6]:
def add_row(A,k,i,j):
    "Add k times row i to row j in matrix A (using 0 indexing)."
    m = A.shape[0]
    E = np.eye(m)
    if i != j:
        E[j,i] = k
    else:
        E[i,j] = k+1
    return E@A

def swap_row(A,i,j):
    "Swap rows i and j matrix A (using 0 indexing)."
    nrows = A.shape[0]
    E = np.eye(nrows)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E@A

def scale_row(A,k,i):
    "Multiply row i by k in matrix (using 0 indexing)."
    nrows = A.shape[0] # The number of rows in A
    E = np.eye(nrows)
    E[i,i] = k
    return E@A

In [8]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
b = np.array([[2],[14],[10]])

In [9]:
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [10]:
M = np.hstack([A,b])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


In [15]:
M1 = scale_row(M,1/6,0)
print(M1)

[[  1.           2.5          0.16666667   0.33333333]
 [  8.           7.          12.          14.        ]
 [  2.           7.           8.          10.        ]]


In [16]:
M2 = add_row(M1,-8,0,1)
print(M2)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]


In [17]:
M3 = add_row(M2,-2,0,2)
print(M3)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]


In [19]:
M4 = scale_row(M3,-1/13,1)
print(M4)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          2.          7.66666667  9.33333333]]


In [20]:
M5 = add_row(M4,-2,1,2)
print(M5)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.           1.          -0.82051282  -0.87179487]
 [  0.           0.           9.30769231  11.07692308]]


In [21]:
M6 = scale_row(M5,1/M5[2,2],2)
print(M6)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          1.          1.19008264]]


In [22]:
M7 = add_row(M6,-M6[1,2],2,1)
print(M7)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.          0.          0.1046832 ]
 [ 0.          0.          1.          1.19008264]]


In [23]:
M8 = add_row(M7,-M7[0,2],2,0)
print(M8)

[[ 1.          2.5         0.          0.13498623]
 [ 0.          1.          0.          0.1046832 ]
 [ 0.          0.          1.          1.19008264]]


In [24]:
M9 = add_row(M8,-M8[0,1],1,0)
print(M9)

[[ 1.          0.          0.         -0.12672176]
 [ 0.          1.          0.          0.1046832 ]
 [ 0.          0.          1.          1.19008264]]


Or, we can do it the easy way:

In [25]:
x = la.solve(A,b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


### Matrix determinant, inverse, transpose and trace

In [26]:
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [27]:
la.det(A)

-725.9999999999999

In [28]:
la.inv(A)

array([[ 0.03856749,  0.15564738, -0.23829201],
       [ 0.05509642, -0.06336088,  0.08815427],
       [-0.05785124,  0.01652893,  0.10743802]])

Notice that we can solve the equation $Ax=b$ using the inverse $x = A^{-1}b$. But this is a bad idea in general because computing the inverse of a large matrix is computationally expensive and unecessary!

In [31]:
A @ la.inv(A)

array([[  1.00000000e+00,   1.70002901e-16,  -6.93889390e-17],
       [ -1.11022302e-16,   1.00000000e+00,   0.00000000e+00],
       [ -1.66533454e-16,   8.32667268e-17,   1.00000000e+00]])

In [32]:
A.T

array([[ 6,  8,  2],
       [15,  7,  7],
       [ 1, 12,  8]])

In [30]:
np.transpose(A)

array([[ 6,  8,  2],
       [15,  7,  7],
       [ 1, 12,  8]])

In [33]:
np.trace(A)

21

In [34]:
6+7+8

21

### Eigenvalues and eigenvectors

Recall, given a square matrix $A$, a vector $\vec{v}$ is an eigenvector for $A$ with eigenvalue $\lambda$ is $A \vec{v} = \lambda \vec{v}$

Let $A$ be any matrix and consider $S = AA^T$. Then $S$ is a symmetric matrix.

A beautiful resylt is that the eigenvalues of a symmetric matrix are real and the eigenvectors are orthogonal.

In [35]:
S = A @ A.T

In [36]:
print(S)

[[262 165 125]
 [165 257 161]
 [125 161 117]]


In [38]:
evals, evecs = la.eig(S)

In [39]:
print(evals)

[ 524.98305893+0.j  101.08481987+0.j    9.93212121+0.j]


In [40]:
evals.dtype

dtype('complex128')

In [41]:
evals = evals.real

In [42]:
print(evals)

[ 524.98305893  101.08481987    9.93212121]


In [43]:
evecs

array([[ 0.61809779,  0.77885992, -0.10645344],
       [ 0.64796584, -0.58146371, -0.49197584],
       [ 0.44507908, -0.23511099,  0.86407606]])

In [46]:
(1/evals[0]) * S @ evecs[:,0]

array([ 0.61809779,  0.64796584,  0.44507908])