# MATH 210 Introduction to Mathematical Computing

## February 5, 2018

1. Array functions (and methods)
2. Array indexing and slicing
3. Array Stacking
4. Paramatric plots
5. Examples

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Array Functions

There are many functions (besides the usual mathematical functions `exp`,`sin`,`cos`,etc.) we can use to cumpute with NumPy arrays. For example, we have `np.sum`, `np.mean`, `np.max`, `np.min`, etc.

To make demonstrating these functions more interesting, let's use NumPy's random number genrators:

In [3]:
M = np.random.randint(0,10,size=(4,3))

In [4]:
print(M)

[[4 7 0]
 [9 5 8]
 [8 1 8]
 [8 9 4]]


In [5]:
np.sum(M)

71

In [6]:
M.sum()

71

In [7]:
np.sum(M,axis=0)

array([29, 22, 20])

In [8]:
np.sum(M,axis=1)

array([11, 22, 17, 21])

In [9]:
M.sum(axis=1)

array([11, 22, 17, 21])

In [11]:
M.mean(axis=1)

array([ 3.66666667,  7.33333333,  5.66666667,  7.        ])

In [12]:
M.prod(axis=0)

array([2304,  315,    0])

## 2. Indexing and slicing

We access entries or subrrays (slices) of NumPy arrays using square bracket notation:

In [17]:
N = np.random.randint(-100,100,size=(3,7))
print(N)

[[  6 -69  29  92  95 -90 -81]
 [ 87 -47 -52 -19  50 -96  27]
 [ 13 -76  41 -23  89  52  -6]]


Select the entry in row at index 2 and column at index 4:

In [18]:
N[2,4]

89

In [19]:
N[0,0]

6

Select the column at index 3:

In [23]:
c=N[:,3]

In [24]:
print(c)

[ 92 -19 -23]


In [25]:
c.ndim

1

In [26]:
c.shape

(3,)

In [27]:
type(c)

numpy.ndarray

The variable `c` is assigned to a 1-dimensional NumPy array of length 3. If we want it to be a 2-dimensional array which is 3 by 1, then we use the reshape array method.

In [30]:
C = c.reshape(3,1)

In [31]:
print(C)

[[ 92]
 [-19]
 [-23]]


In [32]:
C.ndim

2

In [33]:
C.shape

(3, 1)

In [34]:
P = np.random.randint(-50,50,size=(4,4))

In [35]:
print(P)

[[  5  44  42 -33]
 [ 12 -48  26  -9]
 [-39  41   9   7]
 [-23 -41 -49 -11]]


In [36]:
D = P[ 2:4 , 2:4 ]
print(D)

[[  9   7]
 [-49 -11]]


## 3. Array Stacking

We can combine arrays to create larger arrays:

In [3]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))

print(A,'\n')
print(B,'\n')
print(C,'\n')
print(D,'\n')

[[ 1.  1.]
 [ 1.  1.]] 

[[ 2.  2.]
 [ 2.  2.]] 

[[ 3.  3.]
 [ 3.  3.]] 

[[ 4.  4.]
 [ 4.  4.]] 



In [46]:
X1 = np.vstack([A,C])
X2 = np.vstack([B,D])
X = np.hstack([X1,X2])
print(X)

[[ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 3.  3.  4.  4.]
 [ 3.  3.  4.  4.]]


In [48]:
v1 = np.random.randint(0,10,10)
print(v1)
v2 = np.random.randint(0,10,10)
print(v2)

[2 3 9 1 3 4 2 9 6 1]
[6 1 4 6 5 1 0 5 9 6]


In [49]:
B = np.vstack([v1,v2])
print(B)

[[2 3 9 1 3 4 2 9 6 1]
 [6 1 4 6 5 1 0 5 9 6]]


In [52]:
C = np.vstack([v1,v2]).T
print(C)

[[2 6]
 [3 1]
 [9 4]
 [1 6]
 [3 5]
 [4 1]
 [2 0]
 [9 5]
 [6 9]
 [1 6]]
