# MATH 210 Introduction to Mathematical Computing

## March 07, 2018

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as spi
%matplotlib inline

1. Linear algebra in Scipy
    * Matrix multiplication
    * Soving linear system $Ax=b$
    * Determinan, inverse and transpose
    * Eigenvalues and eigenvectors
2. Example

## 1. Linear algerba with Scipy

Many linear algerba functions and operations are avaliable in the subpackage `scipy.linalg`.

In [3]:
import scipy.linalg as la

Recall, Numpy arrays execute operations elementwise.

In [5]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [6]:
A*A

array([[ 1,  4],
       [ 9, 16]])

This is array elementwise multiplication. What about matrix multiplication?

In [7]:
A @ A

array([[ 7, 10],
       [15, 22]])

The symbol `@` is used for matrix multiplication of Numpy arrays. This is new as of Python 3.5.

What about matrix powers such as $A^2$?

In [8]:
print(A)

[[1 2]
 [3 4]]


In [9]:
A**2

array([[ 1,  4],
       [ 9, 16]])

In [11]:
from numpy.linalg import matrix_power as mpow

In [12]:
mpow(A,2)

array([[ 7, 10],
       [15, 22]])

In [14]:
D = np.array([[2,0],[0,-1]])
print(D)

[[ 2  0]
 [ 0 -1]]


In [18]:
mpow(D,5)

array([[32,  0],
       [ 0, -1]])

#### Solving linear systems 

A linear system of equations in matrix form is $Ax=b$ where $A$ is a m by n matrix, $X$ is a vector of size n by 1 and $b$ is a vector of size m by 1. In `scipy.linalg`, there is a function called `scipy.linalg.solve` for solving linear systems.

In [24]:
A = np.random.randint(-5,5,(3,3))
print(A)

[[ 1  4  0]
 [-2 -2 -4]
 [-3 -5 -2]]


In [25]:
b = np.random.randint(-5,5,(3,1))
print(b)

[[-1]
 [ 3]
 [ 3]]


In [26]:
x = la.solve(A,b)
print(x)

[[-0.5   ]
 [-0.125 ]
 [-0.4375]]


In [27]:
A @ x

array([[-1.],
       [ 3.],
       [ 3.]])

Let's write a function called `add_row` which takes input parameters $A$, $k$, $i$ and $j$ and returns the NumPy array resulting from adding $k$ times row $i$ to row $j$.

In [43]:
def add_row(A,k,i,j):
    "Add k times row i to row j in matrix A (using 0 indexing)."
    m = A.shape[0]
    E = np.eye(m)
    if i != j:
        E[j,i] = k
    else:
        E[i,j] = k+1
    return E@A

In [44]:
M = np.array([[1,1],[3,2]])
result = add_row(M,2,0,1)
print(result)
print(np.array([[1,1],[5,4]]))

[[ 1.  1.]
 [ 5.  4.]]
[[1 1]
 [5 4]]


Let's write a function called `swap_row` which takes input parameters $A$, $i$ and $j$ and returns the matrix resulting from swapping rows $i$ nd $J$ in $A$.

In [47]:
def swap_row(A,i,j):
    "Swap rows i and j matrix A (using 0 indexing)."
    nrows = A.shape[0]
    E = np.eye(nrows)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E@A

In [54]:
M = np.array([[1,1],[3,2]])

In [49]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

let's use our array operations to solve $Mx = b$for $b=[-1,1]^T$

In [56]:
b = np.array([[1],[-1]])
print(b)

[[ 1]
 [-1]]


In [57]:
A = np.hstack([M,b])
print(A)

[[ 1  1  1]
 [ 3  2 -1]]


In [58]:
AI = add_row(A,-3,0,1)
print(AI)

[[ 1.  1.  1.]
 [ 0. -1. -4.]]
